Introduce a 23video slide-type
kkos2/os2display-admin pull request #23
Opened 2019-07-02 10:27 UTC by danquah

OSD-62

2019-07-02 11:07 UTC, tripox requested changes

2019-07-02 11:07 UTC, tripox commented on src/twentythree/Resources/public/templates/twentythree/slides/twentythree/twentythree.html
> +<div class="twentythree" style="position: relative">
Seems duplicate - already in the styling.

2019-07-02 11:07 UTC, tripox commented on src/twentythree/Resources/public/templates/twentythree/slides/twentythree/twentythree.html
> +    <div style="width:100%; height:100%; position: relative;">
Consider putting the inline styling in the stylesheet if possible

2019-07-02 11:07 UTC, tripox commented on src/twentythree/Resources/public/templates/twentythree/slides/twentythree/twentythree.js
> +                if (slide.options.sound === 1) {
Should this not be 0? 
The checkbox is enabled sound, not disabling.

2019-07-02 11:07 UTC, tripox commented on src/twentythree/Resources/public/templates/twentythree/slides/twentythree/twentythree.js
> +                slide.url = "//video.kk.dk/v.ihtml/player.html?source=embed&photo%5fid=" + slide.options.id + "&autoPlay=1&loop=1";
Seems very specific for kk.dk?
Shouldn't it be configurable?

2019-07-07 20:37 UTC, danquah commented
@tripox did a fair bit of rework and have (amongst other things) addressed most of your comments. Could I have a re-review pretty please? :)

2019-07-08 08:26 UTC, tripox approved these changes

2019-07-08 08:28 UTC, merged